### ISSUE TITLE
Build a theme for Everest with just CSS!

### ISSUE THREAD

**Issue by RohitAwate** [RohitAwate/Everest#23]
![hacktoberfest](https://user-images.githubusercontent.com/23148259/46293381-f0d1d700-c5b0-11e8-9e8f-5892c17bcef4.png)

I've been planning to add some more colors to Everest. Since its HacktoberFest, here's an opportunity for you to make a meaningful contribution to open-source and win that t-shirt. Just build some colorful themes for Everest. All you need is CSS!

**The best entries may ship with future releases of Everest!**

I've set up a nice [theming guide](https://github.com/RohitAwate/Everest/blob/master/THEMES.md) which you can follow.

# Rules
1. Create a new `themes/` directory and place your CSS file there.
2. Themes should have elegant names. No 'Dark' or 'Light', please. They can imitate other established themes, too.
3. Your theme should cover the entirety of the UI. Partially developed entries will be rejected.
4. Everest is an ongoing project and your themes will be edited in the future when new UI elements are added. You may choose to do so, too.
5. Your CSS file should start with the following comment:
```css
/*
    Name: <ThemeName>
    Author: <YourName> (<GitHubProfileLink>)
*/
```
6. While submitting your PR, make sure you add images showcasing all the UI elements of Everest. This includes the details like the history pane search results, the color of the checkboxes, or even the color of the snackbar popup.

# How will my theme be evaluated?
Your theme will be judged based on the following criteria:
- Aesthetic
- Whether the theme fits with the overall flat design of Everest
- Completeness
- Imitates popular themes _(One Dark or Solarized, for example)_

# Note
I've been planning to create a white and light grey based theme with cornflower blue as the highlight color. If someone can do that and call it _Oasis_, that would be awesome!

Also, Adreana is a bit messy right now, so you may be interested in cleaning it up.

_Happy hacking! :octocat:_

**Comment by Riduidel** [comment]
Could you take a look at https://vscodethemes.com/ and give a list of themes you would like to see ported to Everest ? It will be way easier to create themes with an already existing color palette.

**Comment by RohitAwate** [comment]
@Riduidel I guess the most popular ones would be a good place to start.
Monokai, Monokai++, the variants of Material, Ayu, the default Light theme for VS Code.

However, I don't want to simply encourage the porting over of existing themes. Original creations will be appreciated!

> I've been planning to create a white and light grey based theme with cornflower blue as the highlight color. If someone can do that and call it _Oasis_, that would be awesome!

If you're interested, you could try this.

**Comment by Riduidel** [comment]
Unfortunatly, i've started to take a look at Everest UI, and I couldn't easily understand which color impact which part of screen.
I guess I could launch the FXML with Gluon SceneBuilder (https://gluonhq.com/products/scene-builder/) do you think it could work ?

**Comment by Riduidel** [comment]
Oh crap

	java.io.IOException: javafx.fxml.LoadException: 
	/C:/Users/nicolas-delsaux/Documents/open-source/Everest/src/main/resources/fxml/homewindow/HomeWindow.fxml

		at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:92)
		at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:82)
		at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:97)
		at com.oracle.javafx.scenebuilder.kit.editor.EditorController.updateFxomDocument(EditorController.java:2384)
		at com.oracle.javafx.scenebuilder.kit.editor.EditorController.setFxmlTextAndLocation(EditorController.java:664)
		at com.oracle.javafx.scenebuilder.app.DocumentWindowController.loadFromFile(DocumentWindowController.java:385)
		at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenFiles(SceneBuilderApp.java:634)
		at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenFile(SceneBuilderApp.java:580)
		at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performControlAction(SceneBuilderApp.java:209)
		at com.oracle.javafx.scenebuilder.app.WelcomeDialog.fireOpenProject(WelcomeDialog.java:175)
		at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
		at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
		at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
		at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
		at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
		at javafx.event.Event.fireEvent(Event.java:198)
		at javafx.scene.Node.fireEvent(Node.java:8413)
		at javafx.scene.control.Hyperlink.fire(Hyperlink.java:153)
		at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
		at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
		at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
		at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
		at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
		at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
		at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
		at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
		at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
		at javafx.event.Event.fireEvent(Event.java:198)
		at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
		at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
		at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
		at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
		at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
		at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
		at java.security.AccessController.doPrivileged(Native Method)
		at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
		at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
		at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
		at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
		at com.sun.glass.ui.View.notifyMouse(View.java:937)
		at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
		at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: javafx.fxml.LoadException: 
	/C:/Users/nicolas-delsaux/Documents/open-source/Everest/src/main/resources/fxml/homewindow/HomeWindow.fxml

		at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
		at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2848)
		at javafx.fxml.FXMLLoader.processImport(FXMLLoader.java:2692)
		at javafx.fxml.FXMLLoader.processProcessingInstruction(FXMLLoader.java:2661)
		at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2517)
		at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)
		at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:89)
		... 56 more
	Caused by: java.lang.ClassNotFoundException: com.jfoenix.controls.JFXButton
		at java.lang.ClassLoader.findClass(ClassLoader.java:530)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at javafx.fxml.FXMLLoader.loadTypeForPackage(FXMLLoader.java:2916)
		at javafx.fxml.FXMLLoader.loadType(FXMLLoader.java:2905)
		at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2846)
		... 61 more

**Comment by RohitAwate** [comment]
I'm afraid Adreana is a bit messy and not documented. Scene Builder can help greatly.
You'll need to import JFoenix into SB before opening the FXMLs. I'm using some Material Design widgets from it.

**Comment by Riduidel** [comment]
That's the kind of things that could deserve a paragraph in README ! (I will try to add that if I successfully create a theme)
